{"name": "test_hotstock_get", "status": "broken", "statusDetails": {"message": "NameError: name 'SchemaError' is not defined", "trace": "self = <TestCase.hotstocks.test_hotstocks_get.Testhotstockget object at 0x0000025071B2A550>\n\n    def test_hotstock_get(self):\n        url = HTTP+\"/as_recommend/api/hot_stocks/v1/get\"\n        print(url)\n    \n        paylo = {\"timeStamp\": get_time_stamp13()}\n        sign1 = {\"sign\": get_sign(paylo)}\n        paylo.update(sign1)\n        payload = json.dumps(dict(paylo))\n    \n        headers = JSON1\n    \n        response = requests.request(\"POST\", url, headers=headers, data=payload)\n        r = response.json()\n    \n        assert response.status_code == 200\n        if r.get(\"code\") == \"000000\":\n            assert r.get(\"msg\") == \"ok\"\n            assert r.get(\"data\") != None\n        else:\n            raise AssertionError()\n    \n        schema = r\n        try:\n>           validate(instance=addresultschema, schema=schema, format_checker=draft7_format_checker)\nE           NameError: name 'validate' is not defined\n\ntest_hotstocks_get.py:35: NameError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestCase.hotstocks.test_hotstocks_get.Testhotstockget object at 0x0000025071B2A550>\n\n    def test_hotstock_get(self):\n        url = HTTP+\"/as_recommend/api/hot_stocks/v1/get\"\n        print(url)\n    \n        paylo = {\"timeStamp\": get_time_stamp13()}\n        sign1 = {\"sign\": get_sign(paylo)}\n        paylo.update(sign1)\n        payload = json.dumps(dict(paylo))\n    \n        headers = JSON1\n    \n        response = requests.request(\"POST\", url, headers=headers, data=payload)\n        r = response.json()\n    \n        assert response.status_code == 200\n        if r.get(\"code\") == \"000000\":\n            assert r.get(\"msg\") == \"ok\"\n            assert r.get(\"data\") != None\n        else:\n            raise AssertionError()\n    \n        schema = r\n        try:\n            validate(instance=addresultschema, schema=schema, format_checker=draft7_format_checker)\n>       except SchemaError as e:\nE       NameError: name 'SchemaError' is not defined\n\ntest_hotstocks_get.py:36: NameError"}, "start": 1623839316234, "stop": 1623839316257, "uuid": "d5e65619-d0b3-4849-98b2-06b84976dc84", "historyId": "0ac91a994c4af7f612fde24c4cae7bc9", "testCaseId": "fd21a176f684fdde52a50aa31dc9d66f", "fullName": "TestCase.hotstocks.test_hotstocks_get.Testhotstockget#test_hotstock_get", "labels": [{"name": "parentSuite", "value": "TestCase.hotstocks"}, {"name": "suite", "value": "test_hotstocks_get"}, {"name": "subSuite", "value": "Testhotstockget"}, {"name": "host", "value": "DESKTOP-AEOR74N"}, {"name": "thread", "value": "21520-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.hotstocks.test_hotstocks_get"}]}