{"name": "test_StockSelectionDevice_modify01", "status": "broken", "statusDetails": {"message": "pymysql.err.InternalError: (1049, \"Unknown database 'stock_selector'\")", "trace": "self = <TestCase.StockSelectionDevice.test_StockSelectionDevice_02_modify.TestStockSelectionDeviceModify object at 0x000002181F580B20>\n\n    @allure.story('修改策略_1-中国香港')\n    def test_StockSelectionDevice_modify01(self):\n        q = OperationSql(\"192.168.1.237\", \"root\", \"123456\", \"user_account\")\n        userId = q.show_sql(\"select id from t_user_account where `zr_no`= '68904140';\")\n        q = OperationSql(\"192.168.1.236\", \"root\", \"123456\", \"stock_selector\")\n>       _id = q.show_sql(f\"select _id from t_tactic6 where `user_id`= {userId};\")\n\ntest_StockSelectionDevice_02_modify.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\Common\\show_sql.py:56: in show_sql\n    raise e\n..\\..\\Common\\show_sql.py:52: in show_sql\n    cursor = self.get_newCursor()\n..\\..\\Common\\show_sql.py:33: in get_newCursor\n    self._cursor = self.get_connect_sql().cursor()\n..\\..\\Common\\show_sql.py:27: in get_connect_sql\n    self._conn = pymysql.connect(self.address, self.user, self.password, self.database)\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\__init__.py:94: in Connect\n    return Connection(*args, **kwargs)\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:325: in __init__\n    self.connect()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:599: in connect\n    self._request_authentication()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:861: in _request_authentication\n    auth_packet = self._read_packet()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:684: in _read_packet\n    packet.check_error()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\protocol.py:220: in check_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xff\\x19\\x04#42000Unknown database 'stock_selector'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.InternalError: (1049, \"Unknown database 'stock_selector'\")\n\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\err.py:109: InternalError"}, "start": 1597029947735, "stop": 1597029947770, "uuid": "e74cb55d-14f3-4159-80d6-e06307018725", "historyId": "8dff92072f35e560d80c5814605ae57b", "testCaseId": "05fb960158dfbc3e5d891cb2d478e517", "fullName": "TestCase.StockSelectionDevice.test_StockSelectionDevice_02_modify.TestStockSelectionDeviceModify#test_StockSelectionDevice_modify01", "labels": [{"name": "feature", "value": "选股器"}, {"name": "story", "value": "修改策略_1-中国香港"}, {"name": "parentSuite", "value": "TestCase.StockSelectionDevice"}, {"name": "suite", "value": "test_StockSelectionDevice_02_modify"}, {"name": "subSuite", "value": "TestStockSelectionDeviceModify"}, {"name": "host", "value": "DESKTOP-KBU1G8M"}, {"name": "thread", "value": "74024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.StockSelectionDevice.test_StockSelectionDevice_02_modify"}]}