{"name": "test_identity_valid", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <TestCase.Account.test_open_account.TestClass object at 0x0000023164CBFD30>\n\n    @allure.story(\"资料和OCR识别是否一致\")\n    def test_identity_valid(self):\n        response = zhuorui(\"开户\", \"资料和OCR识别是否一致\")\n>       assert_data(response, \"020011\", \"资料和OCR识别不一致\")\n\ntest_open_account.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>, code = '020011', msg = '资料和OCR识别不一致'\n\n    def assert_data(response: object, code: object, msg: object) -> object:\n>       assert code == response.json().get(\"code\")\nE       AssertionError\n\n..\\..\\Common\\assertapi.py:2: AssertionError"}, "start": 1609913489996, "stop": 1609913490033, "uuid": "e154e139-f2af-4d48-8fc8-d250d9e7bffa", "historyId": "5b3fdd732ff7ab00dd3554149c10b53a", "testCaseId": "ca77c5407744263b2f2582217e1bdf8f", "fullName": "TestCase.Account.test_open_account.TestClass#test_identity_valid", "labels": [{"name": "story", "value": "资料和OCR识别是否一致"}, {"name": "feature", "value": "开户"}, {"name": "parentSuite", "value": "TestCase.Account"}, {"name": "suite", "value": "test_open_account"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-AEOR74N"}, {"name": "thread", "value": "25860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.Account.test_open_account"}]}