{"uuid": "780d2712-5caf-4549-888d-86553c401262", "children": ["a04df0d9-5030-415b-822d-4c785109c4f9", "d0f52cb5-ce6b-4c31-a9da-5c9449bc070c", "6c5e9eac-ff52-4dfd-87a5-916d5d977b06"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\python\\zrapiautotestv1.0\\TestCase\\StockQuotation\\OptionalStock\\test_stick_optional_stock.py\", line 18, in setup_class\n    print(id[-1].get('_id'))\n"}, "start": 1594198705133, "stop": 1594198705183}], "start": 1594198705133, "stop": 1594198705215}