{"uuid": "3bb2889d-d3d2-45ca-85f7-e149f1df9c85", "children": ["fa8a43b8-7872-477b-8a67-7d23a266cdf2", "cd09f598-4f90-4262-9323-d1fdc00601de", "59b776c8-0a07-4da1-acf3-211e6c4aea3b"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\python\\zrapiautotestv1.0\\TestCase\\StockQuotation\\OptionalStock\\test_stick_optional_stock.py\", line 18, in setup_class\n    print(id[-1].get('_id'))\n"}, "start": 1594177082476, "stop": 1594177082518}], "start": 1594177082476, "stop": 1594177082536}