{"name": "test_Astock_F10financial_report_tsException", "status": "broken", "statusDetails": {"message": "pymysql.err.InternalError: (1049, \"Unknown database 't_stock_search'\")", "trace": "cls = <class 'TestCase.StockQuotation.AstockRelevance.test_Astcok_F10financial_report.TestAstockF10financialreport'>\n\n    @classmethod\n    def setup_class(cls) -> None:\n        login()\n        q = OperationSql(\"192.168.1.237\", \"root\", \"123456\", \"t_stock_search\")\n>       stock_code = str(q.show_sql(\"select code from t_stock_search where `ts`= 'HK';\"))\n\ntest_Astcok_F10financial_report.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\Common\\show_sql.py:56: in show_sql\n    raise e\n..\\..\\..\\Common\\show_sql.py:52: in show_sql\n    cursor = self.get_newCursor()\n..\\..\\..\\Common\\show_sql.py:33: in get_newCursor\n    self._cursor = self.get_connect_sql().cursor()\n..\\..\\..\\Common\\show_sql.py:27: in get_connect_sql\n    self._conn = pymysql.connect(self.address, self.user, self.password, self.database)\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\__init__.py:94: in Connect\n    return Connection(*args, **kwargs)\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:325: in __init__\n    self.connect()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:599: in connect\n    self._request_authentication()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:861: in _request_authentication\n    auth_packet = self._read_packet()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\connections.py:684: in _read_packet\n    packet.check_error()\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\protocol.py:220: in check_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xff\\x19\\x04#42000Unknown database 't_stock_search'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.InternalError: (1049, \"Unknown database 't_stock_search'\")\n\nC:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pymysql\\err.py:109: InternalError"}, "start": 1595899181909, "stop": 1595899181909, "uuid": "c9f04912-72e4-47d0-b298-5db6545e41d1", "historyId": "e40d8f8a4cd748f3fc4a3dc5d2f9a086", "testCaseId": "49fa29f255a953ce15b9fa09dbbf7810", "fullName": "TestCase.StockQuotation.AstockRelevance.test_Astcok_F10financial_report.TestAstockF10financialreport#test_Astock_F10financial_report_tsException", "labels": [{"name": "feature", "value": "A股"}, {"name": "story", "value": "A股获取F10财报信息_ts为异常"}, {"name": "parentSuite", "value": "TestCase.StockQuotation.AstockRelevance"}, {"name": "suite", "value": "test_Astcok_F10financial_report"}, {"name": "subSuite", "value": "TestAstockF10financialreport"}, {"name": "host", "value": "DESKTOP-KBU1G8M"}, {"name": "thread", "value": "14488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.StockQuotation.AstockRelevance.test_Astcok_F10financial_report"}]}