{"uuid": "d416cea4-71a2-4603-8bfd-b11a1131a84c", "children": ["3df87c56-b68c-4843-9fbf-e7a9201c5a92", "5e33f65e-c53b-4b84-bac4-264ad601ecdf", "f213b913-d591-4f52-b31e-ec29f930eeaf", "7359835b-d228-4b74-8c51-906c6eceb992", "ff8170b6-ea19-49da-9d87-685f12d5df4f"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'get'\n", "trace": "  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 963, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = next(it)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\Administrator\\Desktop\\apiauto-zhuosui1.5\\TestCase\\MarketQuotation\\test_platedetail.py\", line 13, in setup_class\n    login()\n  File \"C:\\Users\\Administrator\\Desktop\\apiauto-zhuosui1.5\\Common\\login.py\", line 27, in login\n    res = response_login.json().get(\"data\").get(\"token\")\n"}, "start": 1592560873085, "stop": 1592560873110}], "start": 1592560873085, "stop": 1592560873210}