{"uuid": "600ba5be-ccf5-4c43-bf00-4864fde5d414", "children": ["cff273c8-5933-4fa1-915a-6f29e5053e86", "e650769c-6b4a-46f6-b288-9b695ae7801a", "f0a1a3fc-6e05-433e-9d92-4d03bfce8cb8", "907da916-175c-482f-8ca0-74d3ee9eea78", "68a980d1-d234-416d-88a9-17384420bd53"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'get'\n", "trace": "  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 963, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = next(it)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\Administrator\\Desktop\\apiauto-zhuosui1.5\\TestCase\\MarketQuotation\\test_platedetail.py\", line 13, in setup_class\n    login()\n  File \"C:\\Users\\Administrator\\Desktop\\apiauto-zhuosui1.5\\Common\\login.py\", line 27, in login\n    res = response_login.json().get(\"data\").get(\"token\")\n"}, "start": 1592560632637, "stop": 1592560632665}], "start": 1592560632637, "stop": 1592560632768}