{"uuid": "f01c322a-8b8c-4174-beee-5f715f50849d", "children": ["61b3a425-2488-448b-b47d-53a67dc8afb0", "7e49010d-6cd7-4978-a34f-3cbbdd6c7aea", "128cd062-b8c5-4037-bd12-f57582368135", "d650416d-ce38-4179-b7e4-81a596c1a6bf", "0764a6ec-32f9-4cb0-bee1-b9f488a98ec3"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'get'\n", "trace": "  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 963, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in call_fixture_func\n    res = next(it)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Program Files\\python\\python36\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\Administrator\\Desktop\\apiauto-zhuosui1.5\\TestCase\\MarketQuotation\\test_platedetail.py\", line 13, in setup_class\n    login()\n  File \"C:\\Users\\Administrator\\Desktop\\apiauto-zhuosui1.5\\Common\\login.py\", line 27, in login\n    res = response_login.json().get(\"data\").get(\"token\")\n"}, "start": 1592560640473, "stop": 1592560640498}], "start": 1592560640473, "stop": 1592560640592}